### ISSUE TITLE
Strikethrough values are not exported to OTF

### ISSUE THREAD

**Issue by jenskutilek** [Typefounding/underlineStrikethrough#1]
Probably a RoboFont bug ... cf. http://doc.robofont.com/forums/topic/strikeout-values-are-not-written-to-font/

**Comment by benkiel** [comment]
Yes, I think that's a bug in UFO2FDK —I need to do a bit more testing to see if the FDK reading from UFOs sets the value correctly.

For what it's worth, I usually pull the values and add them to a build script that sets the fussier things with TTX.

**Comment by benkiel** [comment]
Closing as something the extension can't do, it just sets values in the UFO
