### ISSUE TITLE
EZUI and UI thoughts

### ISSUE THREAD

**Issue by ryanbugden** [Typefounding/underlineStrikethrough#11]
<img width="916" alt="image" src="https://github.com/Typefounding/underlineStrikethrough/assets/12752088/fe07c5c3-a08b-4e0e-9d9e-27c2ed0f24ba">

Here's a quick sketch of a potential layout shift in the UI, using EZUI—code below. In using the extension, it was unclear to me whether `Apply to All` was going to only set the values within the extension or write them into the UFO. I'd propose there just be one button at the bottom that writes whatever values are set in the extension to all corresponding UFOs (and have Apply to All just populate field for other fonts listed in the extension). I think that'd make it easier to be more fluid with values/fonts while using the extension.

```python
import ezui

class UnderlineStrikethrough(ezui.WindowController):

    def build(self):
        content = """
        * HorizontalStack  
        > |-----| @table
        > |     |
        > |-----|
        
        > * VerticalStack
        >> * MerzView @merzView
        
        >> [_Hlaetyps_]   @testText
        
        >> ---
        
        
        >> * HorizontalStack
        
        >>> * TwoColumnForm   @form1
        >>>> : Underline:
        >>>> [_ _]     @ulThicknessText
        >>>> [_ _]     @ulPosText
        
        >>> * TwoColumnForm   @form2
        >>>> : Strikethrough:
        >>>> [_ _]     @stThicknessText
        >>>> [_ _]     @stPosText
        
        >>> * VerticalStack
        >>>> (Apply to All)        @applyAllButton
        
        ---
        """
        footer="""
        (Set All Values)           @setAllButton
        """
        
        field_value_width = 40
        button_width = 120
        
        descriptionData = dict(
            table=dict(
                items=[
                    "A",
                    "B",
                    "C"
                ],
                width=180,
            ),
            merzView=dict(
                backgroundColor=(1, 1, 1, 1),
                delegate=self,
                height=300
            ),
            testText=dict(
                # trailingText="Testing text",
            ),
            form1=dict(
                titleColumnWidth=90,
                itemColumnWidth=120
            ),
            form2=dict(
                titleColumnWidth=90,
                itemColumnWidth=120
            ),
            ulThicknessText=dict(
                valueWidth=field_value_width,
                trailingText="Thickness",
            ),
            ulPosText=dict(
                valueWidth=field_value_width,
                trailingText="Position",
            ),
            stThicknessText=dict(
                valueWidth=field_value_width,
                trailingText="Thickness",
            ),
            stPosText=dict(
                valueWidth=field_value_width,
                trailingText="Position",
            ),
            applyCurrentButton=dict(
                width=button_width,
            ),
            applyAllButton=dict(
                width=button_width,
            ),
            setAllButton=dict(
                width=button_width,
            ),
        )
        self.w = ezui.EZWindow(
            content=content,
            title='Underline Strikethrough',
            descriptionData=descriptionData,
            controller=self,
            size='auto',
            footer=footer
        )

    def started(self):
        self.w.open()

UnderlineStrikethrough()
```

**Comment by benkiel** [comment]
Ryan — thank you for this, I've not had a chance to look through it all, will take a couple of days

**Comment by benkiel** [comment]
I think that the action button should likely just be "Set Values" and and maybe "Copy to all" instead of "Apply to all"?

**Comment by ryanbugden** [comment]
I like that idea! Was struggling with the wording. To be clear, this is just a UI sketch so far; haven't wired it up at all.

**Comment by ryanbugden** [comment]
All hooked up! 
Feel free to give it a spin if/when you have a chance :)
https://github.com/ryanbugden/underlineStrikethrough/tree/ezui

I've added a few bells and whistles:
- Can select multiple fonts at once and change values for all selected → removed Copy All button
- See what all selected fonts look like at the same time, with ghosted faded overlays
- Stays up to date with all open fonts (even when some open or close), and tries to keep selection
- Can change color of the lines (remembers user setting)
- Remembers user test string
- Convenience buttons for quick-setting the position of the strikethrough
- Reassuring message in-UI when all the values are written into the UFO

What it doesn't do:
- Nicely scale the preview or zoom in/out. Not sure how to implement this with MerzView. Thinking [this](https://typesupply.github.io/merz/views/merzView.html#merz.views.MerzView) might be a good place to start...
- MerzView doesn't change with dark mode.

**Comment by benkiel** [comment]
This looks great, PR?

**Comment by benkiel** [comment]
Closed by #12, thank you Ryan!

**Comment by ryanbugden** [comment]
Thanks!

Just had a thought—which layout do you prefer?

<img width="975" alt="image" src="https://github.com/Typefounding/underlineStrikethrough/assets/12752088/cee18387-9e40-48d5-b27b-a09f992e1c40">
<img width="998" alt="image" src="https://github.com/Typefounding/underlineStrikethrough/assets/12752088/da0e3748-d380-4418-a759-ae76533c6f3a">

**Comment by benkiel** [comment]
I think top, but it's a close call.

**Comment by ryanbugden** [comment]
Cool, let's keep it! I'll sit with the layout and see if there's anything else that comes to mind. 

Thanks for taking the time to look at the adjustments and PR. Exciting :)
