### ISSUE TITLE
Issues with None values

### ISSUE THREAD

**Issue by connordavenport** [Typefounding/underlineStrikethrough#13]
First off, amazing job on the update! 
I ran into an issue when trying to open the extension if no value is already set in the font info. 
I can open a PR if you want, just lmk. Anyways, I tried it out and this seems to work:
```
if font.path not in dictionary.keys() and value:
    dictionary.update({font.path: value})
else:
    dictionary.update({font.path: 0})
```
I also found that if you delete a value from the text fields it becomes `None` and it will throw an error so I just changed the text callbacks to accept this as a value, e.g. `self.underlineThickness[font.path] = 0 if value is None else value`

**Comment by benkiel** [comment]
Oh crud. Ok, I or @ryanbugden will look into and fix

**Comment by ryanbugden** [comment]
Thanks for pointing this out @connordavenport. I'll look into this and fold in your changes with some other minor stuff I have in the works.
