### ISSUE TITLE
Support for showing kerning

### ISSUE THREAD

**Issue by ryanbugden** [Typefounding/underlineStrikethrough#18]
A nice-to-have.

Currently just uses a rudimentary way of advancing the cursor by a glyph width.
https://github.com/Typefounding/underlineStrikethrough/blob/67c2839dd92938a71d915126a6ab868ccc4aa592/Underline%20Strikethrough.roboFontExt/lib/Underline%20StrikeThrough.py#L521C38-L521C38

**Comment by benkiel** [comment]
This isn't needed, not worth effort, tbh

**Comment by ryanbugden** [comment]
Cool with that! Closing :)
