### ISSUE TITLE
Feature Request: Apply Current Values to All

### ISSUE THREAD

**Issue by mrecord** [Typefounding/underlineStrikethrough#20]
In the previous build there was a button to Apply the Current Values to all UFOs. Please bring that back. 

I'm guessing we're supposed to select all ufos when setting the values for everything, but that fuzzy overlay of all styles is kinda weird. I would prefer to set the values in one style and then apply to all (and then select all styles to proof).

P.S. this is a great extension. Simple, easy to use, and powerful.

**Comment by ryanbugden** [comment]
Any thoughts on where the button should be?

**Comment by benkiel** [comment]
Bottom right with a title of "Apply to all UFOs" makes sense to me at least

**Comment by ryanbugden** [comment]
> Bottom right with a title of "Apply to all UFOs" makes sense to me at least

IMO, we can easily run into some of the confusion I was experiencing in the last version. It was unclear to me when things were getting written into UFOs. 

If this feature just applies the values currently shown in the extension to the other fields for all open font references, it's not yet applied to UFOs, so probably shouldn't have the word UFOs in it.

We should workshop a clear name differentiation between this button and the Set Values one.

Long and not catchy name examples:
- Proliferate Values Across All Fonts Here
- Write Values into UFOs

I think it should probably go somewhere here in this zone, keeping what's currently Set Values in its own bottom (final step) area:
<img width="1128" alt="image" src="https://github.com/Typefounding/underlineStrikethrough/assets/12752088/ec10ff0b-4b3f-4542-9ae1-1c3ea1a8c443">

**Comment by ryanbugden** [comment]
Should we keep with the `Sync` theme that's already there near the thickness field?

<img width="1089" alt="image" src="https://github.com/Typefounding/underlineStrikethrough/assets/12752088/93bc161a-9194-4c98-9dd9-f2d132d946c6">

**Comment by benkiel** [comment]
yes, that is much more clear, @mrecord that work for you?

**Comment by mrecord** [comment]
"Sync All Values" doesn't convey enough meaning (synchronize what values to what?). 
Suggestions: Apply Current Values to All, Sync Using Current Values. 

("Write All Values" is good)

**Comment by ryanbugden** [comment]
@mrecord Implemented! Can you test the extension that's currently in the repo before I version up for Mechanic users? Thanks :)

**Comment by mrecord** [comment]
Hi @ryanbugden. Thank you for the update. 
That is exactly the functionality I was looking for. Works like a charm and the wording on the buttons is easy to understand.
Bonus points for the "All values have been written" confirmation message. I didn't know I needed that.
