### ISSUE TITLE
Underline position inaccurate in the preview?

### ISSUE THREAD

**Issue by ryanbugden** [Typefounding/underlineStrikethrough#9]
I’m not sure the underline position is reflected accurately in the preview. In the screenshot, should it be top-aligned to the baseline? (The strikethrough appears to be correct, as 670 = cap-height)
https://learn.microsoft.com/en-us/typography/opentype/spec/post
But I'm also unclear about the two pieces contained within the description from the link above:

> This is the suggested distance of the top of the underline from the baseline (negative values indicate below baseline). 

>The PostScript definition of this FontInfo dictionary key (the y coordinate of the center of the stroke) is not used for historical reasons. The value of the PostScript key may be calculated by subtracting half the underlineThickness from the value of this field.

This is more of a question, because I'm not sure what attribute should be set to what value at whichever point in the compilation process, (and of course the fact that browsers and apps all decide to render things differently adds to the mess).

<img width="633" alt="image" src="https://github.com/Typefounding/underlineStrikethrough/assets/12752088/b1377dd4-b0da-447c-8258-46e70c93c99a">

I'm happy to make a PR, but wanted to confirm whether or not this is right.

**Comment by benkiel** [comment]
Ok, reading through my code, here is the issue:

The UFO spec just has one value for underline position, `postscriptUnderlinePosition` [see here](https://unifiedfontobject.org/versions/ufo3/fontinfo.plist/#postscript-specific-data).

But, as you note above, the postscript version of this info is applied by taking half the value, where the `post` table uses the number as the top of the underline.

So, one needs two numbers or something in the UFO spec that says this is the one spot, to calculate the other: do this. 

When I wrote the code, I went with the postscript way, so it draws the underline with the mid-point at the value given.

I need to do some research into what the FDK and fontMake does with this info, and then also likely something to clear this up in the UFO spec.

**Comment by ryanbugden** [comment]
If FDK/UFO/Fontmake don't change, we could do something like these radio buttons to change the preview.

<img width="916" alt="image" src="https://github.com/Typefounding/underlineStrikethrough/assets/12752088/72322cdd-87f0-47a8-90c7-2ddff4200b30">

**Comment by benkiel** [comment]
Closing this, work to continue in the UFO spec
